import {StyleSheet, Dimensions, Platform} from 'react-native';
import Colors from '../../constants/Colors';

export default StyleSheet.create({
  safeAreaContainer: {
    paddingHorizontal: 24,
    backgroundColor: '#e1342f',
  },
  screen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  BoxShadow: {
    shadowColor: 'black',
    shadowOpacity: 0.25,
    shadowOffset: {width: 0, height: 0},
    shadowRadius: 1,
    elevation: 1,
    // overflow: 'hidden',
  },
  menuItem: {
    textAlign: 'left',
    fontWeight: '700',
    fontSize: 15,
    color: '#2B2C2D',
    fontFamily: 'Gotham',
    alignSelf: 'flex-start',
    marginBottom: 8,
    lineHeight: 16.58,
  },
  wrapperView: {
    borderTopWidth: 1,
    borderTopColor: '#EFEFEF',
    padding: 10,
    marginTop: 10,
  },
  safeAreaContainerLight: {
    backgroundColor: '#FFFFFF',
    height: '100%',
    // fontFamily: 'Gotham-Light',
  },
  MainContainer: {
    backgroundColor: '#E91E05',
    height: '100%',
  },
  MainContainerLight: {
    backgroundColor: '#FFFFFF',
    height: '100%',
    paddingTop: 20,
    // margin: 20,
  },

  highlight: {
    fontWeight: '700',
  },
  row: {
    flex: 1,
    flexDirection: 'row',
    paddingTop: 15,
    paddingBottom: 15,
  },
  inputWrap: {
    flex: 1,
    borderColor: '#cccccc',
    borderBottomWidth: 1,
    marginBottom: 10,
    flexDirection: 'row',
  },
  inputdate: {
    fontSize: 14,
    marginBottom: -12,
  },
  headingText: {
    alignSelf: 'center',
    color: '#FFFFFF',
    fontFamily: 'Gotham',
    fontWeight: '500',
    fontSize: 35,
    // marginTop: 20,
  },
  headingTitle: {
    alignSelf: 'center',
    color: '#000000',
    // fontFamily: 'Gotham-Bold',
    fontSize: 25,
  },
  image: {
    marginTop: 111,

    height: 227,
    width: 274,
    alignSelf: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    color: '#2B2C2D',
    fontWeight: '700',
    marginTop: 49,
    marginLeft: 90,
    marginRight: 90,
    alignSelf: 'center',
    // width: 223,
  },
  sectionDescription: {
    fontSize: 20,
    color: '#2B2C2D',
    fontWeight: '200',
    marginTop: 16,
    marginLeft: 35,
    marginRight: 35,
    alignSelf: 'center',
  },
  bottomText: {
    fontSize: 20,
    color: '#000000',
    fontWeight: '500',
    marginTop: 16,
    marginLeft: 35,
    marginRight: 35,
    textAlign: 'center',
    fontFamily: 'Gotham',
  },

  deliveryView: {
    flexDirection: 'row',
    marginTop: 22,
    marginLeft: 105,
    marginRight: 90,
    alignSelf: 'center',
  },

  deliveryTime: {
    fontSize: 12,
    color: '#2B2C2D',
    fontWeight: '500',
    alignSelf: 'center',
    fontFamily: 'Gotham',
  },
  button1: {
    backgroundColor: 'red',
    height: 49,
    alignItems: 'center',
    borderRadius: 12,
    marginTop: 140,
    marginLeft: 16,
    marginRight: 16,
    color: '#FFFFFF',
    justifyContent: 'center',
  },
  buttonText1: {
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 18,
    color: '#FFFFFF',
  },
  button2: {
    marginTop: 27,
    marginLeft: 133,
    marginRight: 134,
    marginBottom: 53,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText2: {
    color: '#2B2C2D',
    fontWeight: '500',
    fontSize: 18,
    fontFamily: 'Gotham',
  },

  headingDesc: {
    color: '#2B2C2D',
    fontFamily: 'Gotham',
    fontSize: 22,
    fontWeight: '500',
    textAlign: 'center',
    justifyContent: 'center',
  },
  headingDescTwo: {
    color: '#2B2C2D',
    fontFamily: 'Gotham',
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
    justifyContent: 'center',
  },
  descText: {
    color: '#2B2C2D',
    fontFamily: 'Gotham-Light',
    fontSize: 16,
    width: '100%',
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    lineHeight: 18.75,
  },
  descHistoryText: {
    color: '#2B2C2D',
    fontFamily: 'Gotham-Light',
    fontSize: 13,
    textAlign: 'left',
    justifyContent: 'center',
    lineHeight: 18.75,
  },
  descTextLight: {
    color: '#2B2C2D',
    fontFamily: 'Gotham-Light',
    fontSize: 16,
    width: '100%',
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    // marginTop: 5,
  },

  buttonStyle: {
    borderWidth: 1,
    borderColor: '#FFFFFF',
    backgroundColor: '#E91E05',
    borderRadius: 10,
    height: 49,
    alignItems: 'center',
    justifyContent: 'center',
    // width: '90%',
    marginTop: 30,
  },
  container: {
    flex: 1,
    marginTop: 0,
  },
  item: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 32,
  },

  mainBody: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  mapStyle: {
    position: 'relative',
  },

  addressButtonView: {
    width: '100%',
    backgroundColor: '#FFFFFF',
  },
  SectionStyle: {
    flexDirection: 'row',
    height: 20,
    marginTop: 38,
    margin: 8,
  },
  AddAddressStyle: {
    // height: 30,
    marginTop: 38,
  },
  SearchStyle: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    height: 20,
    // marginTop: 35,
    margin: 8,
  },
  ChooseType: {
    flexDirection: 'row',
    marginTop: 8,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },

  buttonGrayStyle: {
    backgroundColor: '#FFFFFF',
    height: 45,
    alignItems: 'center',
    borderRadius: 12,
    borderColor: '#DDDDDD',
    borderWidth: 1,
    marginLeft: 15,
    marginRight: 15,
    color: '#000000',
    marginTop: 40,
    marginBottom: -25,
    justifyContent: 'center',
  },
  buttonTextStyle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    // fontFamily: 'Gotham-Bold',
  },
  buttonTextGratStyle: {
    color: '#000000',
    fontSize: 16,
    // fontFamily: 'Gotham-Bold',
  },

  inputStyle: {
    flex: 1,
    borderBottomWidth: Platform.OS === 'android' ? 0 : 1,
    borderBottomColor: '#dadae8',
    fontSize: 16,
    color: Colors.textColor,
    fontFamily: 'Gotham-Light',
    lineHeight: 16,
    marginLeft: 6,
    height: Platform.OS === 'android' ? 40 : 20,
    marginRight: 6,
  },

  searchField: {
    flex: 1,
    borderBottomWidth: 0,
    height: Platform.OS === 'android' ? 40 : 20,
    color: '#A2A2A2',
    lineHeight: 16,
    fontSize: 14,
    fontFamily: 'Gotham',
    fontWeight: '200',
  },
  inputPhone: {
    fontFamily: 'Gotham',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpTextBox: {
    flex: 1,
    color: 'black',
    paddingLeft: 15,
    paddingRight: 15,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: Colors.primaryColor,
    fontSize: 16,
    height: 50,
    width: 50,
    fontFamily: 'Gotham-Light',
    margin: 10,
    textAlign: 'center',
  },
  FollowBox: {
    flex: 1,
    color: 'black',
    // paddingLeft: 15,
    paddingRight: 20,
    fontSize: 16,
    height: 34,
    width: 34,
    margin: 10,
    resizeMode: 'contain',
  },
  sectionThree: {
    color: 'black',
    margin: 10,
    padding: 20,
    justifyContent: 'center',
  },
  OTPTextField: {
    color: 'black',
    margin: 10,
    padding: 20,
    justifyContent: 'center',
    borderColor: '#DDDDDD',
    borderWidth: 1,
  },
  registerTextStyle: {
    color: Colors.textColor,
    textAlign: 'center',
    fontWeight: '500',
    fontFamily: 'Gotham-Light',
    fontSize: 12,
    alignSelf: 'center',
    justifyContent: 'center',
    padding: 3,
  },
  registerTextStyleRed: {
    marginTop: Platform.OS === 'android' ? 10 : 0,
    color: Colors.primaryColor,
  },
  headerTitle: {
    color: Colors.textColor,
    fontFamily: 'Gotham',
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 17.23,
  },
  navBackButton: {
    width: 12,
    height: 21,
    marginLeft: 16,
    resizeMode: 'contain',
  },
  textTitle: {
    fontWeight: '700',
    color: '#2B2C2D',
    fontFamily: 'Gotham',
    fontSize: 18,
    alignSelf: 'flex-start',
    textAlign: 'center',
    justifyContent: 'center',
    margin: 10,
    marginTop: 20,
    lineHeight: 20,
  },
  itemTitle: {
    fontSize: 12,
    color: '#2B2C2D',
    fontFamily: 'Gotham',
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    height: 50,
  },
  prodDescText: {
    color: '#2B2C2D',
    marginLeft: 10,
    marginRight: 10,
    fontSize: 13,
    fontFamily: 'Gotham',
  },
  prodDescTextLight: {
    color: '#2B2C2D',
    fontSize: 14,
    fontFamily: 'Gotham-Light',
  },
  rateText: {
    color: '#2B2C2D',
    fontSize: 18,
    fontFamily: 'Gotham',
    fontWeight: '500',
  },
  centerTextStyle: {
    color: '#2B2C2D',
    textAlign: 'center',
    fontSize: 16,
    fontFamily: 'Gotham',
    fontWeight: '500',
    lineHeight: 18.75,
  },
  CategoryView: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    height: 180,
    width: 150,
    marginTop: 20,
    marginRight: 20,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 12,
  },
  // New Added Css
  aboutPageTitle: {
    color: Colors.textColor,
    fontFamily: 'Gotham',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'left',
  },
  aboutPageDesc: {
    color: Colors.textColor,
    fontFamily: 'Gotham',
    fontSize: 12,
    flex: 1,
    alignSelf: 'center',
    textAlign: 'left',
    justifyContent: 'center',
    marginTop: 12,
    marginBottom: 12,
  },
});
